### ISSUE TITLE
Simplified Chinese support

### ISSUE THREAD

**Issue by fengchaobio** [sawhney17/logseq-pdf-export#1]
Great plugin, but it seems like no support for simplified Chinese in my Mac. Is it possible to support Chinese？
<img width="590" alt="image" src="https://user-images.githubusercontent.com/65841298/160313073-2f9132dd-7954-42fe-95c0-8a38c65fd8f2.png">

**Comment by GatherStar** [comment]
Same question. （同样的问题。）


![image](https://user-images.githubusercontent.com/50571479/160316301-1f750ae3-106f-4e87-8d22-e2125066874f.png)

**Comment by sawhney17** [comment]
I'll look into making this possible

**Comment by sawhney17** [comment]
New release has this feature
