### ISSUE TITLE
Can not find the PDF printer

### ISSUE THREAD

**Issue by pys1992** [sawhney17/logseq-pdf-export#10]
logseq version: 0.6.5

<img width="611" alt="image" src="https://user-images.githubusercontent.com/44765369/163541361-2e5d41ce-f6bd-4431-98dd-c44ea04d2a4d.png">

**Comment by sawhney17** [comment]
Just click the PDF button on the bottom left corner and then click save to PDF when the option pops up

**Comment by pys1992** [comment]
> Just click the PDF button on the bottom left corner and then click save to PDF when the option pops up
> On 15 Apr 2022, 11:47 AM +0400, pys ***@***.***>, wrote:
> > logseq version: 0.6.5
> > —
> > Reply to this email directly, view it on GitHub, or unsubscribe.
> > You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
> 

It works. Thank you very much.
