### ISSUE TITLE
Empty lines get ignore, breaks formatting

### ISSUE THREAD

**Issue by WeisseTeetasse** [sawhney17/logseq-pdf-export#11]
Empty lines get ignored when exporting, which breaks intentional formatting 

in Logseq:
![Screenshot 2022-04-24 at 20 39 00](https://user-images.githubusercontent.com/68740702/164991473-1d36c1e9-1714-4c68-b14c-9ad4546215c6.png)

exported:
![Screenshot 2022-04-24 at 20 39 09](https://user-images.githubusercontent.com/68740702/164991486-c50b3224-f136-4e37-87fd-c5559115b0f1.png)

**Comment by sawhney17** [comment]
Fixed in a recent version
