### ISSUE TITLE
Cannot read properties of null

### ISSUE THREAD

**Issue by bran112299** [sawhney17/logseq-pdf-export#13]
![image](https://user-images.githubusercontent.com/15021936/166063486-fc84e5eb-f9fb-45f8-b98d-0d6ca0f7df52.png)

Everytime i select a template this shows up on console, not sure what the problem is but I cant export no matter what.

**Comment by bran112299** [comment]
![image](https://user-images.githubusercontent.com/15021936/166063862-d02ec421-df5d-431d-b0b7-78777b91761e.png)
Here is another error I get too.

**Comment by sawhney17** [comment]
Should work now. Try the new version.

**Comment by sawhney17** [comment]
Are you on the latest version of the plug-in?
