### ISSUE TITLE
Only inherits *some* of the theme making fonts blurry

### ISSUE THREAD

**Issue by WeisseTeetasse** [sawhney17/logseq-pdf-export#15]
I got NEON theme installed and exported a journal page

This is what it looks in Logseq:
![Screenshot 2022-05-07 at 23 23 10](https://user-images.githubusercontent.com/68740702/167272125-faa4daf7-95d0-4d91-87ce-f9d35ab04ef7.png)

This is what it looks on pdf:
![Screenshot 2022-05-07 at 23 23 05](https://user-images.githubusercontent.com/68740702/167272135-9bad98e6-2fe4-4735-be25-cf49fbfce694.png)

Notice how the Headings are blurry, background color is not there.

Also bold is not working:

![Screenshot 2022-05-07 at 23 25 35](https://user-images.githubusercontent.com/68740702/167272172-a4afc1bf-f9f4-4c0c-9b25-92a12bc44778.png)

![Screenshot 2022-05-07 at 23 26 03](https://user-images.githubusercontent.com/68740702/167272186-1a4ce847-f430-46a1-919b-2cd6b57bfed1.png)

**Comment by sawhney17** [comment]
Try the new 4th option called print with retained formatting :)
