### ISSUE TITLE
Latex "\sqrt{}" does not display correctly 

### ISSUE THREAD

**Issue by skydtrtzmr** [sawhney17/logseq-pdf-export#18]
Hi, thank you for the plugin!
I have tried the "print with retained formatting" option, which helps a lot :)
Unfortunately, when there is a `\sqrt{}` expression (latex)  :
![image](https://user-images.githubusercontent.com/45526359/167753927-8f009d90-4de7-4c6d-bba8-0b508d3fea3d.png)

the expected rendering is like that (in logseq):
![image](https://user-images.githubusercontent.com/45526359/167753942-8531cc2e-7fb5-4b02-a38f-2cd9167b70a0.png)

but when exported to pdf (via "print with retained formatting"), the output seems wrong as seen in the image:
![image](https://user-images.githubusercontent.com/45526359/167753974-ecd65be1-93a7-48d5-8ab2-722b077890ed.png)
(same in different PDF reader)

Thank you for your effort!（＾-＾）

**Comment by sawhney17** [comment]
Should be fixed for the retained formatting now
