### ISSUE TITLE
Templates config doesnt work

### ISSUE THREAD

**Issue by Rafcienko** [sawhney17/logseq-pdf-export#19]
I'm following you instructions but the plug in only work with the default at the bottom choice. 
When I'm trying to use template that I filled in it doesnt show them in the menu and the export fails.
![Skärmavbild 2022-05-11 kl  17 47 36](https://user-images.githubusercontent.com/104384953/167892940-bf86a9cf-b913-4e93-973a-7bed4080d5c6.png)
![Skärmavbild 2022-05-11 kl  17 47 16](https://user-images.githubusercontent.com/104384953/167892945-96022b58-2ab6-4719-8ad9-47f46af0daee.png)
![Skärmavbild 2022-05-11 kl  17 46 25](https://user-images.githubusercontent.com/104384953/167892947-c9b81c47-9454-4f33-9d23-3914a2245076.png)
![Skärmavbild 2022-05-11 kl  17 46 17](https://user-images.githubusercontent.com/104384953/167892948-37d9bd13-74a0-47e1-a7c4-e607b2759812.png)

**Comment by acsr** [comment]
@sawhney17 can you manage to catch that context and warn?
