### ISSUE TITLE
Support Image & Table

### ISSUE THREAD

**Issue by emms007** [sawhney17/logseq-pdf-export#2]
We commonly use md-tables and picture in our graph.
Could this be integrated in the PDF output?

**Table block:**
```| Syntax      | Description | Test Text     |
  | :---        |    :----:   |          ---: |
  | Header      | Title       | Here's this   |
  | Paragraph   | Text        | And more      |
```
**Logseq Visual:**
![image](https://user-images.githubusercontent.com/171033/160355825-bae6189e-ea7f-429a-8708-335eb26f65d8.png)

The logseq special block formatters is also interesting:
```
#+BEGIN_IMPORTANT
hello
#+END_IMPORTANT
```
**PDF output:**
![image](https://user-images.githubusercontent.com/171033/160355981-5a8e946b-d48b-4f54-9d76-9525019a9d0b.png)

**Comment by sawhney17** [comment]
Images should already be implemented, could you send me a screenshot of the image when in edit mode?

**Comment by emms007** [comment]
Sure, the block above is 👍 
![image](https://user-images.githubusercontent.com/171033/160596602-50331034-4ff1-4ccf-b212-23fab0a8e932.png)

**Comment by sawhney17** [comment]
Which platform are you on?

**Comment by emms007** [comment]
Windows 10, usual Chrome. Nothing particular

**Comment by lukas-mertens** [comment]
@sawhney17 This sounds like a permission problem with the file api: @emms007 most likely it is going to work, if you use logseq via the electron app. Maybe Chrome only gave permissions to the other directory and now it is not possible for the plugin to access the path `../assets`as it is one directory level higher?!

**Comment by h-b** [comment]
Images also do not work for me. In logseq, I write for example

`![testing.svg](../assets/testing_1648672201459_0.svg){:width 300, :height 200}`

which displays the image in logseq. But in the PDF it looks like this:

![image](https://user-images.githubusercontent.com/24413995/161989595-7ae6f9b4-8f5b-4d26-b534-c5954fe5bbe5.png)

This happens also for png files. I am on Linux using Zorin OS 16.1 (based on Ubuntu focal).

Thank you.

**Comment by emms007** [comment]
Checking again the problem seems easy to fix:

1. In Logseq Electron normal image display, the path is as below:
`assets://E:/Documents/X.ESC/X/SyncthingCloudLink/logseq-master/assets/image_1644840950240_0.png`

2. While, in the PDF generation template, it goes out as :
`E:/Documents/X.ESC/X/SyncthingCloudLink/logseq-master/assets/image_1644840950240_0.png`
=> it misses assets:// which if added works OK

**Comment by sawhney17** [comment]
Both of these issues should be fixed in the latest release. I've added support for tables and MD images and _majorly_ refactored the code to use native APIs and print screens. Hopefully this should work a _lot_ better

**Comment by sawhney17** [comment]
Images should already be functioning can you send me the image link? Rather what you see when you enter edit mode for the image?

I'll see what can happen about tables

**Comment by sawhney17** [comment]
I'm working on a new approach to the plug-in using native electron APIs, should have a version out tomorrow which should drastically improve these.
