### ISSUE TITLE
How can l download the exported pdf

### ISSUE THREAD

**Issue by mendax1234** [sawhney17/logseq-pdf-export#24]
My question is the same as the title.
My version of logseq is 0.6.9. My operating system is windows10

**Comment by sawhney17** [comment]
Could you send a screenshot of what you're seeing?

**Comment by mendax1234** [comment]
l think there is no need to have a screenshot since when l export it to pdf. It seems that it will go the the print page directly. And l even can't see where the pdf is and how is the pdf.

**Comment by sawhney17** [comment]
Which platform are you on? Just change the printer from the bottom to PDF and click save as pdf

**Comment by mendax1234** [comment]
logseq 0.6.9 on windows 10.

>Just change the printer from the bottom to PDF and click save as pdf
Where is it? Can you provide a photo or a screenshot?

**Comment by sawhney17** [comment]
I'm not on windows, could you send a screenshot of the print dialogue I'm not sure how it looks on windows

**Comment by sawhney17** [comment]
Follow these steps https://browserhow.com/how-to-print-website-and-save-as-pdf-in-chrome-computer/

**Comment by mendax1234** [comment]
@sawhney17 Can edge do this?

**Comment by mendax1234** [comment]
Thanks l find that , but there are some pages that l don't need. How to delete them?

**Comment by sawhney17** [comment]
Sorry I don't think I get what you're saying. Would you like to delete pages you downloaded or delete them in logseq?

**Comment by mendax1234** [comment]
Delete the pages l download. 
For example, l have on page in the logseq , but after converting it to the html by your plugins , it will have more pages than l expect. For examle ,it has 4 pages now.

**Comment by mendax1234** [comment]
l find the the links are also included in the pdf. But l only want the content but not the link.

**Comment by sawhney17** [comment]
Right. You can open this in any Pdf app like acrobat and delete or move pages there.

**Comment by sawhney17** [comment]
hide links via the command "Command c command b" for removing the bullets

**Comment by mendax1234** [comment]
![image](https://user-images.githubusercontent.com/62934294/169943990-ab70de8e-6c8a-4860-839d-a654d04eb673.png)
I mean this link. How can l hide them?

**Comment by sawhney17** [comment]
Go to plugin settings and turn on the hide linked references option

**Comment by mendax1234** [comment]
It seems that it does not have an effect.

**Comment by sawhney17** [comment]
It should, can you send a screenshot of your settings?

**Comment by mendax1234** [comment]
Sorry for causing you so much trouble. After l refresh my logseq , it works!

**Comment by sawhney17** [comment]
Excellent!
