### ISSUE TITLE
Templates not Working

### ISSUE THREAD

**Issue by solariz** [sawhney17/logseq-pdf-export#25]
Hey,

on my Windows Machine everyything works fine but on my Linux Desktop (popOS: GNOME + Ubuntu) unfortunately I can only use the Option "Print with retained formatting" no matter what If I click the Template Buttons just nothing happens.

Is there a way to activate somekind of debug / logging to find what may cause that?

Thank you

**Comment by sawhney17** [comment]
There is a console accessible via control  shift i

Try checking that for errors.

**Comment by solariz** [comment]
ok, if I click on one of the Template buttons I immediatly receive this console error:

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'replace')
    at zl (index.0630bad3.js:140)
    at Ac (index.0630bad3.js:142)
zl @ index.0630bad3.js:140
Ac @ index.0630bad3.js:142
async function (async)
Ac @ index.0630bad3.js:142
t @ index.0630bad3.js:50
mh @ index.0630bad3.js:39
vh @ index.0630bad3.js:39
yh @ index.0630bad3.js:39
mu @ index.0630bad3.js:39
Rp @ index.0630bad3.js:39
(anonymous) @ index.0630bad3.js:39
dp @ index.0630bad3.js:43
hh @ index.0630bad3.js:39
zp @ index.0630bad3.js:39
Kc @ index.0630bad3.js:39
Yc @ index.0630bad3.js:39
t.unstable_runWithPriority @ index.0630bad3.js:28
Mn @ index.0630bad3.js:39
pp @ index.0630bad3.js:43
Oh @ index.0630bad3.js:39
```

Following the Debug the line causing the exception is:
```js
var n = t.replace(/:LOGBOOK:|collapsed:: true/gi, "");
```

**Comment by adxsoft** [comment]
Same problem occurs on Mac OSX version Logseq 0.7.6

**Comment by sawhney17** [comment]
@adxsoft this is a different error. What's happening is that you don't have a page open. Click the title of the journal page so that you can't scroll and it should work.

**Comment by sawhney17** [comment]
@solariz, it should work now

**Comment by 5cat** [comment]
Hello @sawhney17 ,
i'm having the same behavior on linux. Cant use the templates. Here is what i got in the traceback.
![image](https://user-images.githubusercontent.com/42038325/186834906-7b25b1b0-190a-4e38-9a2c-52c377373c16.png)

**Comment by sawhney17** [comment]
Are you using the latest version of the plugin? Could you click the index.537 thing and send a screenshot of the highlighted line.

**Comment by 5cat** [comment]
Yes I'm running the latest version 2.2.5.
this is the file is in `.logseq/plugins/logseq-pdf-export-plugin/dist/assets/index.537a73ae.js`
its shasum is `88b07967841d1bbeed8d8275f35c96c9c14a7e53`
the exact line that the error happen is 
```js
id:: `))}var $d=new KW().use(og).use(eZ);$d.inline.ruler.enable(["mark"]);async function Ac(t,e=void 0,n=void 0){var r;if(n!=null)throw oZ(),logseq.hideMainUI(),setTimeout(iZ,100),"No text to print";const o=await logseq.Editor.getCurrentPageBlocksTree();if(e!=null)Rf(await logseq.Editor.getBlock(e,{includeChildren:!0})),logseq.settings.blockExportHandling=="Keep title as name of page"?r=`# ${(await logseq.Editor.getCurrentPage()).originalName}`:logseq.settings.blockExportHandling=="Keep title as heading of block"?r=`# ${(await logseq.Editor.getBlock(e)).content}`:r="";else{for(const u in o)Rf(o[u]);r=`# ${(await logseq.Editor.getCurrentPage()).originalName}`}if(logseq.settings[`${t}Choice`]=="Bullets for non top level elements"){for(const u in Ue)if(console.log("Hi"),!(Ue[u].uuid==e&&logseq.settings.blockExportHandling=="Keep title as heading of block"&&e!=null)){var i=await zl(Ue[u][0],t);if(Ue[u][1]>1){i="- "+i;for(let k=1;k<Ue[u][1];k++)i="  "+i}console.log(i),r=`${r}

```
it happens in this part `await zl(Ue[u][0],t)`
and here is the start of the zl function
```js
async function zl(t,e){var n=t.replaceAll(/:LOGBOOK:|collapsed:: true/gi,"");n...
```
note that i tried the same thing in windows and it gave the same error.

**Comment by sawhney17** [comment]
Cool. I’ve got my SATs tomorrow, will fix it on Sunday.

**Comment by adxsoft** [comment]
Yep that did the trick..thanks
