### ISSUE TITLE
[Feature Request]hide the border when click "Print With Retained Formatting"

### ISSUE THREAD

**Issue by yunshuaipeng** [sawhney17/logseq-pdf-export#28]
Hi, is there a way to hide the border when click "Print With Retained Formatting"

<img width="900" alt="image" src="https://user-images.githubusercontent.com/44765369/186910637-d277ed25-5b66-457a-b09d-42d4f3b82f83.png">

**Comment by sawhney17** [comment]
Perhaps you could enable document mode?
I could alternatively add a configuration setting where you can define a custom css selector to hide. But will only be able to get to it on Sunday.

**Comment by pys1992** [comment]
> Perhaps you could enable document mode? I could alternatively add a configuration setting where you can define a custom css selector to hide. But will only be able to get to it on Sunday.
> […](#)
> On 26 Aug 2022 at 5:10 PM +0400, pys ***@***.***>, wrote: Hi, is there a way to hide the border when click "Print With Retained Formatting" — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

How to enable document mode?

**Comment by sawhney17** [comment]
Use the keyboard shortcut "t d"

**Comment by pys1992** [comment]
> Use the keyboard shortcut "t d"
> […](#)
> On 26 Aug 2022 at 6:01 PM +0400, pys ***@***.***>, wrote: > Perhaps you could enable document mode? I could alternatively add a configuration setting where you can define a custom css selector to hide. But will only be able to get to it on Sunday. > … > On 26 Aug 2022 at 5:10 PM +0400, pys @.>, wrote: Hi, is there a way to hide the border when click "Print With Retained Formatting" — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.> How to enable document mode? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

If I enable document mode, the border is not printed. But also I can not get the bullets.
