### ISSUE TITLE
"skip to main content" appears at the bottom of the pdf page

### ISSUE THREAD

**Issue by ANNOARK** [sawhney17/logseq-pdf-export#29]
The file exported with **"Print with retained formatting"** has a text block **"skip to main content"** at the bottom of each page (see picture), which obscures the original text. 
The last page does not have this text block in the same place.
----

![image](https://user-images.githubusercontent.com/43340211/188808854-2d1a450d-8e97-4437-bf09-ee6793303818.png)

**Comment by sawhney17** [comment]
Do you have any other plug is installed?

**Comment by wchisenski** [comment]
I'm seeing the same issue on macOS 12.6 and 0.8.6. I have uninstalled all other plugins to rule that out. I have also tested using several different themes, including the default light theme, bear light and Bonofix Theme. It only appears on documents that are longer than one page. Also note, when using the Dev Theme the plugin will not generate a PDF longer than a single page (even if the content is).

**Comment by sawhney17** [comment]
If you scroll to the bottom does it work?

**Comment by wchisenski** [comment]
Scrolling to the bottom does not resolve either issue. On multi-page content, you still get the **Skip to main content** message on each page. As for the Dev Theme, it still prints only a single page with the content you have displayed in Logseq itself.

**Comment by ANNOARK** [comment]
I haved test uninstalling all plugin, using default theme and scroll to the bottom avoid lazy-load.
None of them work, the question still there 😿.

**Comment by soehl85** [comment]
friends any progress on this? :) kind regards from Switzerland

**Comment by sawhney17** [comment]
try the latest version :)

**Comment by soehl85** [comment]
> try the latest version :)

THANKS
