### ISSUE TITLE
plugin does not work on an offline computer

### ISSUE THREAD

**Issue by liconge** [sawhney17/logseq-pdf-export#3]
So does this plugin only work for computer with internet connection? tried it on an offline computer, when click pdf export, the logseq window turns gray and can't return to normal window unless restart logseq.

**Comment by sawhney17** [comment]
This should work in the latest release

**Comment by liconge** [comment]
Thank you for the reply, it seems none of any installed plugins work on my offline computer, so it is not the plugin problem.
