### ISSUE TITLE
Code blocks are ignored

### ISSUE THREAD

**Issue by iamkroot** [sawhney17/logseq-pdf-export#33]
It seems that code blocks are not supported as yet.

The following markdown:
````
- This is a normal line  
-  
  ```
	  This is inside a code block
	  
	  # this is not a heading
	  
	  this should _not_ be emphasized
	  
	  End of code block
  ```
- This is a normal line again  
-
````

Generates [this pdf](https://github.com/sawhney17/logseq-pdf-export/files/9935589/output.pdf) where the lines inside the codeblock are improperly formatted.

![Screenshot_20221104_115035](https://user-images.githubusercontent.com/29517049/199905310-ebc3d7de-5052-4ca4-92c1-fa62a0e58c2b.png)

Also, it seems the bullets are also broken.

**Comment by sdasda7777** [comment]
Yup, this is so annoying!

**Comment by sdasda7777** [comment]
I'll look into this ASAP 😄

**Comment by sdasda7777** [comment]
I managed to implement partial (as in just a few languages) code highlighting using CodeMirror, but it's painful to work with. Languages must be added individually when creating the CodeMirror view, and not all languages seem to even have a package that would provide the highlighting.

![image](https://github.com/sawhney17/logseq-pdf-export/assets/17746796/a8cb015f-505a-4e32-b6ef-a29f78afc87b)
