### ISSUE TITLE
Unclear usage documentation

### ISSUE THREAD

**Issue by nickpnmrv** [sawhney17/logseq-pdf-export#4]
Thanks for developing! Awesome idea!
Unfortunately, I cannot understand how to use it... how do I define a template? In the settings, there is some css input and options. It doesn't matter what I select, I always get an empty pdf. DO you have some examples on how to actually use this plugin?

**Comment by nickpnmrv** [comment]
I was able to set it up, but still no idea on how to use templates in the configuration. Any example would be appreciated. Thank you in advance!

**Comment by sawhney17** [comment]
Essentially templates are just a way to add custom css. In the place where they ask you for the CSS just paste it into the text field. You can also choose between a few options that are in built such an inherit CSS from logseq theme. To access settings go to plug-ins page and from the page click together icon and then open in settings
