### ISSUE TITLE
Not working for a block view

### ISSUE THREAD

**Issue by nickpnmrv** [sawhney17/logseq-pdf-export#5]
When selecting a block and then clicking on the export, pdf is empty
![Screenshot 2022-04-04 at 17 57 25](https://user-images.githubusercontent.com/28644944/161584094-777cd2cf-f306-45f8-af9d-66aacb12e494.png)
![Screenshot 2022-04-04 at 17 58 37](https://user-images.githubusercontent.com/28644944/161584279-ab3e07d1-b23d-43c8-a314-78486e8b5275.png)
![Screenshot 2022-04-04 at 18 01 35](https://user-images.githubusercontent.com/28644944/161584871-6250ef86-e769-4e6b-a42f-d75d03da78f1.png)

**Comment by sawhney17** [comment]
Thanks for this. It's an unfortunate limitation of logseq at the moment, i'll see if i can work around it.

**Comment by laike9m** [comment]
+1, hope it gets supported soon

**Comment by laike9m** [comment]
Not sure if it helps, but https://github.com/sethyuan/logseq-plugin-doc can export blocks, may serve as a reference.

**Comment by sawhney17** [comment]
Try the new 4th option called print with retained formatting in the latest version :)
