### ISSUE TITLE
A little Benchmark and a few ideas on how to improve the output

### ISSUE THREAD

**Issue by lukas-mertens** [sawhney17/logseq-pdf-export#9]
Hey,

I just did a little Benchmark with a few typical things to see how good the output looks. This is my result.

[Logseq PDF Export Benchmark.pdf](https://github.com/sawhney17/logseq-pdf-export/files/8453446/Logseq.PDF.Export.Benchmark.pdf)

**And this is how it looks in Logseq**
<img width="855" alt="image" src="https://user-images.githubusercontent.com/10901304/162475817-6f9afeb2-735e-4eca-b88c-e104965dc309.png">
<img width="910" alt="image" src="https://user-images.githubusercontent.com/10901304/162477289-f73ba316-4036-4b70-9f40-b9a31ddb472f.png">

<img width="831" alt="image" src="https://user-images.githubusercontent.com/10901304/162475977-233bd370-a5a9-4f1b-93f1-fc818661b22b.png">

As you can see, it does look way better in Logseq. But that is probably because of the way you handle printing: As far as I understand you use the native print-dialog, therefore the theme would have to use`@media print` CSS to style the output.

This sounds like a great approach, as it allows the result to be customizable via CSS. Maybe, however, you could add another option, which could lead to very pretty results: Chrome has a feature, which allows you to print in a wysiwyg-fashion, meaning it prints exactly as shown in Logseq. This could make it easy to render even custom elements added by other plugins.

https://superuser.com/questions/846082/how-to-get-wysiwyp-print-what-you-see-in-a-web-browser

I don't know if it is possible to access these APIs from JavaScript, but it would be very cool. You could just hide things like the menubar and we would get an output which looks exactly like in Logseq. What do you think?

**Comment by sawhney17** [comment]
I tried the approach and it wasn't really working because the print dialogue firstly printed the top bar, but more importantly only printed what was shown on screen and nothing that was shown off the screen. This is partly due to the weather Logseq handles blocks on large pages. I noticed that there was a lot of space on the top and bottom. Are you not exporting an A4?

How does the preview Windows look, as a approach I've  taken is to first convert the blocks in the page to HGML, then apply CSS and finally use the native print dialogue to print what's on the screen.

And have you selected the inherits CSS option in settings?

**Comment by sawhney17** [comment]
I believe that you can add custom CSS. You can go to plug-in settings and edit custom  CSS and other settings for the plug-in from there Including the option to inherit from your current log 16

**Comment by lukas-mertens** [comment]
Yes, I used the default settings for the templates. Inherits css is enabled in template 1, which I used. 

The css to hide everything which should be hidden for printing should be:
```css
.cp__sidebar-help-btn,#left-sidebar,#right-sidebar,#head {
  display: none !important;
}
#main-container {
  padding-left: 0 !important;
}
```

I then used the developer tools to set the page to an appropriate resolution by using the "responsive" feature:
<img width="559" alt="image" src="https://user-images.githubusercontent.com/10901304/162502469-2b3f5a1d-3f74-4253-ae2f-772462278f5f.png">
You can then use the "capture full size screenshot"-function to export an image with full resolution.
<img width="471" alt="image" src="https://user-images.githubusercontent.com/10901304/162502648-2057acba-6932-406a-9eac-e5ed5ed01479.png">
This results in a screenshot like this (right now I don't have the bear theme set up in my browser and the image didn't load properly, but it should demonstrate my point):
![logseq com_ (2)](https://user-images.githubusercontent.com/10901304/162502731-4f013648-713d-43a5-b270-39703f93c187.png)

**Comment by LarsJaeger** [comment]
I dont know what I'm doing wrong, inherit Logseq CSS as well as manually setting css for Templates does not work for me, it all looks like the following screenshot:
![2022-04-28_11-59-35](https://user-images.githubusercontent.com/61934397/165728434-873df065-c316-4291-8552-f5bced3aaa52.png)

**Comment by sawhney17** [comment]
Try the new 4th option called print with retained formatting :)
